config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'profile#index'

  #creates the resources needed to upload a new avatar
  get 'avatar/edit', to: 'avatars#edit', as: 'edit_avatar'
  put 'avatar', to: 'avatars#update', as: 'avatar'
  patch 'avatar', to: 'avatars#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/avatar.rb
class Avatar < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #even though this is a has_one relationship, we will still keep track of all the previous avatars the user has had, but by setting has_one, when 'current_user.avatar' is called, only the last will be displayed
  has_one :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #Sends the user to the login page if they are not logged in, before viewing ANY page
    before_action :authenticate_user!

 
    ########  All steps below this are to add 'first_name and last_name' to the user  ########
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
    ############  End all first_name and last_name  ##############################
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    def edit
        @avatar = current_user.avatar
        @avatar ||= Avatar.new
    end

    def update
        byebug()
    end
end

app/controllers/profile_controller.rb
# This is not a plutal file name, as it uses the users model, so we will only see one 

class ProfileController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/avatars/edit.html.erb
<h1>Edit Avatar</h1>

<%= form_with model: @avatar, url: avatar_path, method: :patch, local: true do |form| %>
    <div>
        <%= form.file_field :image %>
        <%= form.submit %>
    </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
     <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Profile", root_path, class: "nav-item nav-link active" %>
        <%= link_to "Feed", root_path, class: "nav-item nav-link active" %>
        <%= link_to "Upload Photo", root_path, class: "nav-item nav-link active" %>
        <%= link_to "Logout", destroy_user_session_path, class: "nav-item nav-link active", method: "delete" %>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DelayGem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav" if user_signed_in? %>
    

    <div class="container">
      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>  
  </body>
</html>